version: 1
services:
  - type: web
    name: vue-app
    env: node
    buildCommand: npm run build
    startCommand: npx serve -s dist -l $PORT
    routes:
      - type: redirect
        source: "/*"
        destination: "/index.html"
