version: 1
services:
  - type: web
    name: vue-app
    env: node
    buildCommand: npm run build
    startCommand: npx serve -s dist
    routes:
      - source: "/*"
        destination: "/index.html"
